# Generated by Django 5.1.7 on 2025-03-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='labor',
        ),
        migrations.CreateModel(
            name='LaborRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needed_labor', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_requirements', to='callManager.event')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='labor_requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='callManager.laborrequirement'),
        ),
        migrations.CreateModel(
            name='LaborType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_types', to='callManager.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='laborrequirement',
            name='labor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callManager.labortype'),
        ),
        migrations.DeleteModel(
            name='Labor',
        ),
        migrations.AlterUniqueTogether(
            name='laborrequirement',
            unique_together={('event', 'labor_type')},
        ),
    ]
