# Generated by Django 5.1.7 on 2025-03-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0002_remove_assignment_labor_laborrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labortype',
            name='default_rate',
        ),
        migrations.RemoveField(
            model_name='labortype',
            name='description',
        ),
    ]
