# Generated by Django 5.1.7 on 2025-03-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0003_remove_labortype_default_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborrequirement',
            name='rate',
        ),
    ]
