# Generated by Django 5.1.7 on 2025-03-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0004_remove_laborrequirement_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='city',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='state',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.AddField(
            model_name='worker',
            name='labor_types',
            field=models.ManyToManyField(blank=True, related_name='workers', to='callManager.labortype'),
        ),
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
