# Generated by Django 5.1.7 on 2025-03-21 13:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0005_remove_worker_city_remove_worker_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaborRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('load_in_response', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'Other')], max_length=20, null=True)),
                ('load_out_response', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'Other')], max_length=20, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('labor_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callManager.laborrequirement')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callManager.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
