# Generated by Django 5.1.7 on 2025-03-21 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0006_laborrequest_delete_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='load_in_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='load_out_time',
        ),
        migrations.CreateModel(
            name='CallTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_times', to='callManager.event')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='laborrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='laborrequirement',
            name='call_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labor_requirements', to='callManager.calltime'),
        ),
        migrations.AlterUniqueTogether(
            name='laborrequirement',
            unique_together={('call_time', 'labor_type')},
        ),
        migrations.RemoveField(
            model_name='laborrequirement',
            name='event',
        ),
    ]
