# Generated by Django 5.1.7 on 2025-03-21 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0007_remove_event_load_in_time_remove_event_load_out_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborrequest',
            old_name='load_in_response',
            new_name='response',
        ),
        migrations.RemoveField(
            model_name='laborrequest',
            name='load_out_response',
        ),
    ]
