# Generated by Django 5.1.7 on 2025-03-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0008_rename_load_in_response_laborrequest_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='requested',
            field=models.BooleanField(default=False),
        ),
    ]
