# Generated by Django 5.1.7 on 2025-03-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0009_laborrequest_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
