# Generated by Django 5.1.7 on 2025-03-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0010_laborrequest_sms_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
        migrations.AddField(
            model_name='calltime',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
