# Generated by Django 5.1.7 on 2025-03-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0011_remove_event_event_date_calltime_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_single_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
