# Generated by Django 5.1.7 on 2025-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0012_event_end_date_event_is_single_day_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborrequest',
            name='response_message',
        ),
        migrations.AlterField(
            model_name='laborrequest',
            name='response',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=20, null=True),
        ),
    ]
