# Generated by Django 5.1.7 on 2025-03-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0013_remove_laborrequest_response_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='event_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
