# Generated by Django 5.1.7 on 2025-03-26 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0014_laborrequest_event_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='workers', to='callManager.company'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='labor_types',
            field=models.ManyToManyField(blank=True, to='callManager.labortype'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, default='UNNAMED', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(default='12345677890', max_length=15),
            preserve_default=False,
        ),
    ]
