# Generated by Django 5.1.7 on 2025-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0015_worker_companies_worker_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sms_consent',
            field=models.BooleanField(default=False),
        ),
    ]
