# Generated by Django 5.1.7 on 2025-03-29 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0016_worker_sms_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='stop_sms',
            field=models.BooleanField(default=False),
        ),
    ]
