# Generated by Django 5.1.7 on 2025-03-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0017_worker_stop_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='sent_consent_msg',
            field=models.BooleanField(default=False),
        ),
    ]
