# Generated by Django 5.1.7 on 2025-03-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0018_worker_sent_consent_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='slug',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laborrequirement',
            name='slug',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
