# Generated by Django 5.1.7 on 2025-03-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0020_populate_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='calltime',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calltime',
            name='original_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
