# Generated by Django 5.1.7 on 2025-03-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0021_calltime_last_modified_calltime_original_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
