# Generated by Django 5.1.7 on 2025-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0022_calltime_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='nocallnoshow',
            field=models.IntegerField(default=0),
        ),
    ]
