# Generated by Django 5.1.7 on 2025-04-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0023_worker_nocallnoshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrequest',
            name='response',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('ncns', 'No Call No Show')], max_length=20, null=True),
        ),
    ]
