# Generated by Django 5.1.7 on 2025-04-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0024_alter_laborrequest_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='per_page_preference',
            field=models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=10),
        ),
    ]
