# Generated by Django 5.1.7 on 2025-04-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0025_manager_per_page_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callManager.calltime')),
                ('labor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='callManager.laborrequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callManager.worker')),
            ],
            options={
                'unique_together': {('labor_request', 'worker', 'call_time')},
            },
        ),
    ]
