# Generated by Django 5.1.7 on 2025-04-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0027_manager_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_time', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_breaks', to='callManager.timeentry')),
            ],
        ),
    ]
