# Generated by Django 5.1.7 on 2025-04-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0028_mealbreak'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealbreak',
            name='break_type',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid 1-Hour Walk-Away')], default='paid', max_length=10),
        ),
    ]
