# Generated by Django 5.1.7 on 2025-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0029_mealbreak_break_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealbreak',
            name='break_type',
            field=models.CharField(choices=[('paid', 'Paid 30min'), ('unpaid', 'Unpaid 1hr')], default='paid', max_length=10),
        ),
    ]
