# Generated by Django 5.1.7 on 2025-04-13 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0030_timeentry_total_hours_alter_mealbreak_break_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='total_hours',
        ),
    ]
