# Generated by Django 5.1.7 on 2025-04-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0031_remove_timeentry_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='meal_penalty_trigger_time',
            field=models.PositiveIntegerField(default=5, help_text='Hours after start time to trigger meal penalty'),
        ),
    ]
