# Generated by Django 5.1.7 on 2025-04-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0032_company_meal_penalty_trigger_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laborrequest',
            old_name='response',
            new_name='availability_response',
        ),
        migrations.AddField(
            model_name='laborrequest',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborrequest',
            name='is_reserved',
            field=models.BooleanField(default=False, help_text='Reserve this position for the worker'),
        ),
        migrations.AddField(
            model_name='laborrequirement',
            name='fcfs_positions',
            field=models.PositiveIntegerField(default=0, help_text='Number of positions filled by First Come First Served'),
        ),
    ]
