# Generated by Django 5.1.7 on 2025-04-23 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0035_clockintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockintoken',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clock_in_tokens', to='callManager.worker'),
        ),
        migrations.AlterUniqueTogether(
            name='clockintoken',
            unique_together={('event', 'worker')},
        ),
    ]
