# Generated by Django 5.1.7 on 2025-04-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0036_clockintoken_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hour_round_up',
            field=models.PositiveIntegerField(default=15, help_text='Minutes to round up hours worked'),
        ),
    ]
