# Generated by Django 5.1.7 on 2025-04-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0037_company_hour_round_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockintoken',
            name='qr_sent',
            field=models.BooleanField(default=False),
        ),
    ]
