# Generated by Django 5.1.7 on 2025-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0039_worker_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='time_tracking',
            field=models.BooleanField(default=False, help_text='Enable time tracking for this company'),
        ),
    ]
