# Generated by Django 5.1.7 on 2025-04-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0040_company_time_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='minimum_hours',
            field=models.PositiveIntegerField(default=4, help_text='Minimum hours for a call time'),
        ),
    ]
