# Generated by Django 5.1.7 on 2025-04-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0045_ownerinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerinvitation',
            name='company_name',
        ),
        migrations.AddField(
            model_name='ownerinvitation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
