# Generated by Django 5.1.7 on 2025-04-29 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0048_stewardinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stewardinvitation',
            name='phone',
        ),
        migrations.AddField(
            model_name='stewardinvitation',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steward_invitations', to='callManager.worker'),
        ),
    ]
