# Generated by Django 5.1.7 on 2025-04-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0049_remove_stewardinvitation_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stewardinvitation',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steward_invitations', to='callManager.worker'),
        ),
    ]
