# Generated by Django 5.1.7 on 2025-05-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0051_temporaryscanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('minimum_hours', models.PositiveIntegerField(blank=True, help_text='Minimum hours for a call time (defaults to company value if blank)', null=True)),
                ('meal_penalty_trigger_time', models.PositiveIntegerField(blank=True, help_text='Hours after start time to trigger meal penalty (defaults to company value if blank)', null=True)),
                ('hour_round_up', models.PositiveIntegerField(blank=True, help_text='Minutes to round up hours worked (defaults to company value if blank)', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_profiles', to='callManager.company')),
            ],
        ),
    ]
