# Generated by Django 5.1.7 on 2025-05-04 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0052_locationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callManager.locationprofile'),
        ),
    ]
