# Generated by Django 5.1.7 on 2025-05-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0053_event_location_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='minimum_hours',
            field=models.PositiveIntegerField(blank=True, help_text="Minimum hours for this call time (defaults to event's location profile or company)", null=True),
        ),
    ]
