# Generated by Django 5.1.7 on 2025-05-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0054_calltime_minimum_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequirement',
            name='minimum_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum hours for this labor requirement (defaults to call time)', null=True),
        ),
    ]
