# Generated by Django 5.1.7 on 2025-05-08 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0058_alter_worker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
