# Generated by Django 5.1.7 on 2025-05-08 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0059_event_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrequest',
            name='labor_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_requests', to='callManager.laborrequirement'),
        ),
    ]
