# Generated by Django 5.1.7 on 2025-05-08 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0060_alter_laborrequest_labor_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_location',
        ),
    ]
