# Generated by Django 5.1.7 on 2025-05-13 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0062_onetimelogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborrequest',
            name='time_change_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TimeChangeConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('labor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_change_confirmations', to='callManager.laborrequest')),
            ],
        ),
    ]
