# Generated by Django 5.1.7 on 2025-05-13 23:01

import django.db.models.deletion
from django.db import migrations, models

def migrate_companies_to_company(apps, schema_editor):
    Worker = apps.get_model('callManager', 'Worker')
    for worker in Worker.objects.all():
        companies = worker.companies.all()
        if companies.exists():
            # Take the first company if worker has any
            worker.company = companies.first()
            worker.save()

class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0063_laborrequest_sent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='callManager.company'),
        ),
        migrations.RunPython(
            migrate_companies_to_company,
            migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='worker',
            name='companies',
        ),
    ]
