# Generated by Django 5.1.7 on 2025-05-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0065_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
