# Generated by Django 5.1.7 on 2025-05-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0066_company_zip_code_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborrequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_requests', to='callManager.worker'),
        ),
    ]
