# Generated by Django 5.2.3 on 2025-08-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0068_company_name_short_alter_manager_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_short',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
