# Generated by Django 5.2.3 on 2025-08-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0069_alter_company_name_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='token_short',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
