# Generated by Django 5.2.3 on 2025-08-21 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0070_laborrequest_token_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerinvitation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='laborrequest',
            name='token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
