# Generated by Django 5.2.3 on 2025-10-23 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0071_managerinvitation_phone_alter_laborrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laborrequest',
            name='time_change_confirmed',
        ),
    ]
