# Generated by Django 5.2.3 on 2025-11-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0072_remove_laborrequest_time_change_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
