# Generated by Django 5.2.3 on 2025-11-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0073_company_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name_short',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
