# Generated by Django 5.2.3 on 2025-11-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0075_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='call_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='callManager.calltime'),
        ),
    ]
