# Generated by Django 5.2.3 on 2025-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0077_notifications_labor_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='response',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], max_length=20, null=True),
        ),
    ]
