# Generated by Django 5.2.3 on 2025-11-27 23:55
# callManager/migrations/0080_calltime_call_unixtime.py

from django.db import migrations, models
from django.utils import timezone
import datetime


def populate_call_unixtime(apps, schema_editor):
    CallTime = apps.get_model('callManager', 'CallTime')

    to_update = []
    for ct in CallTime.objects.filter(date__isnull=False, time__isnull=False).iterator():
        # Combine date + time → naive datetime
        naive_dt = datetime.datetime.combine(ct.date, ct.time)

        # Make it timezone-aware using the current active time zone
        # (this works the same whether USE_TZ is True or False)
        aware_dt = timezone.make_aware(naive_dt)

        # Convert to UTC and get Unix timestamp
        utc_dt = aware_dt.astimezone(datetime.UTC)          # ← this is the correct way now
        ct.call_unixtime = int(utc_dt.timestamp())
        to_update.append(ct)

    if to_update:
        CallTime.objects.bulk_update(to_update, ['call_unixtime'])


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0079_useradmin_laborrequest_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='call_unixtime',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(populate_call_unixtime, reverse_code=migrations.RunPython.noop),
    ]
