# Generated by Django 5.2.3 on 2025-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0080_calltime_call_unixtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltime',
            name='call_unixtime',
            field=models.BigIntegerField(),
        ),
    ]
