# Generated by Django 5.2.3 on 2025-12-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0081_alter_calltime_call_unixtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
