# Generated by Django 5.2.3 on 2025-12-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0082_owner_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='steward',
            name='per_page_preference',
            field=models.PositiveIntegerField(choices=[(10, '10'), (25, '25'), (50, '50'), (100, '100')], default=10),
        ),
    ]
