# Generated by Django 5.2.3 on 2026-01-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0083_steward_per_page_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='timechangeconfirmation',
            name='cant_do_it',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timechangeconfirmation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
