# Generated by Django 5.2.3 on 2026-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0084_timechangeconfirmation_cant_do_it_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='response',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Time Change', 'Time Change')], max_length=20, null=True),
        ),
    ]
