# Generated by Django 5.2.3 on 2026-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0085_alter_notifications_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='response',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Time Change', 'Time Change'), ('Worker Canceled', 'Worker Canceled')], max_length=20, null=True),
        ),
    ]
