# Generated by Django 5.2.3 on 2026-01-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0086_laborrequest_canceled_alter_notifications_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='canceled_requests',
            field=models.IntegerField(default=0),
        ),
    ]
