# Generated by Django 5.2.3 on 2026-01-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0087_worker_canceled_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='response',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Time Change', 'Time Change'), ('Canceled', 'Canceled')], max_length=20, null=True),
        ),
    ]
