# Generated by Django 5.2.3 on 2026-01-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0088_alter_notifications_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
