# Generated by Django 6.0.1 on 2026-01-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0090_event_hour_round_up_event_meal_penalty_trigger_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltime',
            name='time_has_changed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
