# Generated by Django 6.0.1 on 2026-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0091_calltime_time_has_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='meal_penalty_diff',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Meal penalty multiplier', max_digits=4),
        ),
    ]
