# Generated by Django 6.0.1 on 2026-01-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0092_company_meal_penalty_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='round_up_target',
            field=models.PositiveIntegerField(default=30, help_text='Minutes to round up to'),
        ),
    ]
