# Generated by Django 6.0.1 on 2026-01-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0093_company_round_up_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='round_up_target',
            field=models.PositiveIntegerField(choices=[(30, '30 minutes'), (0, '1 Hour')], default=30, help_text='Round up target'),
        ),
    ]
