# Generated by Django 6.0.1 on 2026-01-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0094_alter_company_round_up_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborrequest',
            name='ncns',
            field=models.BooleanField(default=False),
        ),
    ]
