# Generated by Django 6.0.1 on 2026-02-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0095_laborrequest_ncns'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtoken',
            name='veri_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationtoken',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='stewardinvitation',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steward_invitations', to='callManager.worker'),
        ),
    ]
