# Generated by Django 6.0.1 on 2026-02-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0096_registrationtoken_veri_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_steward',
            field=models.BooleanField(default=False),
        ),
    ]
