# Generated by Django 6.0.1 on 2026-02-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callManager', '0097_worker_is_steward'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_to_send', models.DateTimeField()),
                ('call_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='callManager.calltime')),
            ],
        ),
    ]
