"""
Django settings for callman project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get('DEBUG') == 'True':
    DEBUG = True
else:
    DEBUG = False

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    'theme',
    'callManager.apps.CallmanagerConfig',
    'django_htmx',
    'channels',
    'stripe',
    'rest_framework',
    'api',
    'rest_framework.authtoken',
    'corsheaders',
]
if os.environ.get('DJANGO_ENV') != 'production':
    INSTALLED_APPS.append('django_browser_reload')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'corsheaders.middleware.CorsMiddleware',


]
if os.environ.get('DJANGO_ENV') != 'production':
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')

ROOT_URLCONF = 'callman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

WSGI_APPLICATION = 'callman.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE'),
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'HOST': os.environ.get('DB_HOST'), 
        'PORT': os.environ.get('DB_PORT'),
    }
}


## email section
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587  # This is the default port for TLS, change if your server uses a different port
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER')
SERVER_EMAIL = os.environ.get('EMAIL_HOST_USER')


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'callManager.validators.NonWhitespaceCharacterValidator',
    },
]

# tailwindcss settings
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = [
    '127.0.0.1',
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# callman/settings.py
#LOGGING = {
#    'version': 1,
#    'disable_existing_loggers': False,
#    'handlers': {
#        'console': {
#            'class': 'logging.StreamHandler',
#        },
#    },
#    'loggers': {
#        'callManager.views': {
#            'handlers': ['console'],
#            'level': 'DEBUG',
#        },
#    },
#}

# twilio settings
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER')
TWILIO_ENABLED = os.environ.get('TWILIO_ENABLED')


# login
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'  # Already set, but confirm
LOGOUT_REDIRECT_URL = '/login/'

USE_TZ = False
TIME_ZONE = 'America/New_York'  # Fallback, though Manager.timezone will override

# CORS settings
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS').split(',')

if os.environ.get('DJANGO_ENV') == 'production':
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{asctime} - {name} - {levelname} - {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': '/var/log/django/django_debug.log',
                'formatter': 'verbose',
            },
            'failed_login_file': {
                'level': 'WARNING',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': '/var/log/django/failed_login.log',
                'formatter': 'simple',
                'maxBytes': 10485760,  # 10MB
                'backupCount': 5,
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'callManager': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'api': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'django': {
                'handlers': ['file'],
                'level': 'WARNING',
                'propagate': True,
            },
            'django.security.failed_login': {
                'handlers': ['failed_login_file'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }

else:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'verbose': {
                'format': '{asctime} - {name} - {levelname} - {message}',
                'style': '{',
            },
            'simple': {
                'format': '{levelname} {message}',
                'style': '{',
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'class': 'logging.FileHandler',
                'filename': '/var/log/django/django_debug.log',
                'formatter': 'verbose',
            },
            'failed_login_file': {
                'level': 'WARNING',
                'class': 'logging.handlers.RotatingFileHandler',
                'filename': '/var/log/django/failed_logins.log',
                'maxBytes': 5242880,  # 5 MB
                'backupCount': 5,
                'formatter': 'simple',
            },
            'console': {
                'level': 'INFO',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
        },
        'loggers': {
            'callManager': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'api': {
                'handlers': ['file', 'console'],
                'level': 'DEBUG',
                'propagate': True,
            },
            'django': {
                'handlers': ['file'],
                'level': 'WARNING',
                'propagate': True,
            },
            'django.security.failed_login': {
                'handlers': ['failed_login_file'],
                'level': 'WARNING',
                'propagate': False,
            },
        },
    }


#    LOGGING = {
#        'version': 1,
#        'disable_existing_loggers': False,
#        'formatters': {
#            'verbose': {
#                'format': '{asctime} {name} {levelname} {message}',
#                'style': '{',
#            },
#            'simple': {
#                'format': '{levelname} {message}',
#                'style': '{',
#            },
#            'failed_login': {
#                'format': '{asctime} {levelname} {message} - {request} - {credentials}',
#                'style': '{',
#            },
#        },
#        'handlers': {
#            'file': {
#                'level': 'DEBUG',
#                'class': 'logging.FileHandler',
#                'filename': BASE_DIR / 'logs/django_debug.log',
#                'formatter': 'verbose',
#            },
#            'console': {
#                'level': 'INFO',
#                'class': 'logging.StreamHandler',
#                'formatter': 'simple',
#            },
#            'daphne_file': {
#                'level': 'DEBUG',
#                'class': 'logging.FileHandler',
#                'filename': BASE_DIR / 'logs/daphne.log',
#                'formatter': 'verbose',
#            },
#            'failed_login_file': {
#                'level': 'WARNING',
#                'class': 'logging.FileHandler',
#                'filename': BASE_DIR / 'logs/failed_login.log',
#                'formatter': 'failed_login',
#            },
#        },
#        'loggers': {
#            # Your app
#            'callManager': {
#                'handlers': ['file', 'console'],
#                'level': 'DEBUG',
#                'propagate': False,
#            },
#            # Django
#            'django': {
#                'handlers': ['file'],
#                'level': 'WARNING',
#                'propagate': False,
#            },
#            # === CRITICAL FOR WEBSOCKETS ===
#            'daphne': {
#                'handlers': ['daphne_file', 'console'],
#                'level': 'DEBUG',
#                'propagate': False,
#            },
#            'channels': {
#                'handlers': ['file', 'console'],
#                'level': 'DEBUG',
#                'propagate': False,
#            },
#            'channels.server': {
#                'handlers': ['file', 'console'],
#                'level': 'DEBUG',
#                'propagate': False,
#            },
#            'channels.consumer': {
#                'handlers': ['file', 'console'],
#                'level': 'DEBUG',
#                'propagate': False,
#            },
#            'django.security.failed_login': {
#                'handlers': ['failed_login_file'],
#                'level': 'WARNING',
#                'propagate': False,
#            },
#        },
#    }
#
ASGI_APPLICATION = 'callman.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('localhost', 6379)],
        },
    },
}

#else:
#

FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWS_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "x-frontend-origin",
]
