from django.urls import path
from .views import (
        login_view,
        logout,
        user_info,
        skills_list,
        location_profiles,
        forgot_password,
        reset_password,
        )
from api.view_files import (
        event_views,
        request_views,
        sms_views,
        worker_views,
        call_times,
        time_tracking,
        owner_dashboard,
        user_views,
        contact_views,
        )
from api.view_files.event_views import send_event_messages, confirm_requests
from api.view_files.notifications import notifications, mark_as_read, delete_notification, clear_all_notifications, clear_read_notifications


urlpatterns = [
    path('login/', login_view),
    path('forgot-password/', forgot_password),
    path('reset-password/<uuid:token>/', reset_password),
    path('user/info/', user_info),
    path('steward/register/<uuid:token>/', user_views.resolve_steward_token),
    path('user/register/start/', user_views.start_user_registration),
    path('user/register/', user_views.user_registration),
    path('user/profile/', user_views.user_profile),
    path('logout/', logout),
    path('events/list/', event_views.list_events),
    path('steward/events/', event_views.steward_events),
    path('stewards/', event_views.list_stewards),
    path('create-event/', event_views.create_event),
    path('skills/', skills_list),
    path('event/<slug:slug>/', event_views.event_details),
    path('event/<slug:slug>/assign-steward/', event_views.assign_steward),
    path('event/<slug:slug>/send-messages/', send_event_messages),
    path('event/<slug:slug>/confirm/<event_token>/', confirm_requests),
    path('notifications/', notifications),
    path('notifications/<int:notification_id>/read/', mark_as_read),
    path('notifications/<int:notification_id>/delete/', delete_notification),
    path('notifications/clear-all/', clear_all_notifications),
    path('notifications/clear-read/', clear_read_notifications),
    path('call-time/<slug:slug>/add-call-time/', call_times.add_call_time),
    path('event/<slug:slug>/send-messages/', send_event_messages),
    path('event/<slug:slug>/confirm/<event_token>/', confirm_requests),
    path('notifications/', notifications),
    path('notifications/<int:notification_id>/read/', mark_as_read),
    path('notifications/<int:notification_id>/delete/', delete_notification),
    path('notifications/clear-all/', clear_all_notifications),
    path('notifications/clear-read/', clear_read_notifications),
    path('call-time/<slug:slug>/add-call-time/', call_times.add_call_time),
    path('call-times/<slug:slug>/send-reminder/', call_times.send_reminder),
    path('call-times/<slug:slug>/send-messages/', call_times.send_call_time_messages),
    path('call-times/<slug:slug>/edit/', call_times.edit_call_time),
    path('call-times/<slug:slug>/tracking/', time_tracking.call_time_tracking),
    path('call-times/<slug:slug>/confirmations/', call_times.call_time_confirmations),
    path('call-time/<slug:slug>/copy/', call_times.copy_call_time),
    path('call-times/<slug:slug>/delete/', call_times.delete_call_time),
    path('call/confirm-time-change/<uuid:token>/', call_times.confirm_time_change_api),
    path('upcoming-event-count/', event_views.upcoming_event_count),
    path('pending-count/', request_views.pending_count),
    path('declined-count/', request_views.declined_count),
    path('sms-count/', sms_views.sms_count),
    path('workers/', worker_views.list_workers),
    path('workers/import/', worker_views.import_workers),
    path('workers/import-contacts/', worker_views.import_contacts_json),
    path('workers/<slug:slug>/history/', worker_views.worker_history),
    path('call-times/<slug:slug>/add-labor/', call_times.add_labor_to_call),
    path('call-times/<slug:slug>/requests/', request_views.call_time_list),
    path('labor/<slug:slug>/status/', call_times.labor_requirement_status),
    path('request/<token>/action/', request_views.request_action),
    path('user/request/<token>/action/', request_views.user_request_action),
    path('request/<slug:slug>/fill-list/', request_views.fill_labor_request_list),
    path('request/<slug:slug>/worker/', request_views.request_worker),
    path('request/<slug:slug>/send-messages/', request_views.send_labor_requirement_messages),
    path('labor/<slug:slug>/edit/', call_times.edit_labor_requirement),
    path('labor/<slug:slug>/delete/', call_times.delete_labor_requirement),
    path('location-profiles/', location_profiles),
    path('company/settings/', owner_dashboard.owner_dashboard),
    path('send-steward-invite/', owner_dashboard.send_steward_invite),
    path('confirm/bulk/', call_times.bulk_confirm_requests),
    path('clock-in/<uuid:token>/', time_tracking.worker_clock_in_out_api),
    path('clock-in-qr/<uuid:token>/', time_tracking.worker_qr_clock),
    path('event/<slug:slug>/generate-station/', event_views.generate_signin_station),
    path('station/<uuid:token>/validate/', time_tracking.validate_station),
    path('station/<uuid:token>/clock/', time_tracking.station_clock),
    path('contact/', contact_views.contact_form),
]
